"""JAI - Professional Writer Module
Handles professional writing tasks: emails, proposals, reports, cover letters.
"""

import re
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class ProfessionalWriter:
    """Professional writing assistance for business and formal documents"""
    
    # Templates for different writing tasks
    EMAIL_TEMPLATES = {
        'business': {
            'subject': "Business Proposal: {topic}",
            'body': """Dear {recipient},

I hope this message finds you well. I am writing to discuss {topic}.

{details}

I look forward to your positive response. Please let me know if you would like to schedule a call to discuss this further.

Best regards,
{signature}"""
        },
        'thank_you': {
            'subject': "Thank You - {topic}",
            'body': """Dear {recipient},

Thank you very much for {topic}. I truly appreciate your time and consideration.

{details}

I look forward to continuing our conversation.

Warm regards,
{signature}"""
        },
        'follow_up': {
            'subject': "Following Up: {topic}",
            'body': """Dear {recipient},

I hope you're having a great week. I'm writing to follow up on {topic}.

{details}

Please let me know if you need any additional information from my end.

Best regards,
{signature}"""
        },
        'apology': {
            'subject': "Apology Regarding {topic}",
            'body': """Dear {recipient},

Please accept my sincere apologies for {topic}.

{details}

I assure you that steps have been taken to prevent this from happening again.

Sincerely,
{signature}"""
        },
        'request': {
            'subject': "Request Regarding {topic}",
            'body': """Dear {recipient},

I am writing to kindly request {topic}.

{details}

Thank you for considering my request. I look forward to your favorable response.

Respectfully,
{signature}"""
        },
        'meeting': {
            'subject': "Meeting Request: {topic}",
            'body': """Dear {recipient},

I would like to schedule a meeting to discuss {topic}.

{details}

Please let me know your availability for a {duration} meeting.

Looking forward to connecting,

Best regards,
{signature}"""
        },
        'introduction': {
            'subject': "Introduction: {topic}",
            'body': """Dear {recipient},

I hope this message finds you well. My name is {name}, and I am reaching out to introduce myself regarding {topic}.

{details}

I would love the opportunity to connect and explore potential synergies.

Warmly,
{signature}"""
        },
        'proposal': {
            'subject': "Proposal: {topic}",
            'body': """Dear {recipient},

I am pleased to submit this proposal regarding {topic}.

**Executive Summary**
{executive_summary}

**Proposed Solution**
{solution}

**Timeline & Deliverables**
{timeline}

**Investment**
{investment}

I look forward to discussing this proposal with you.

Sincerely,
{signature}"""
        }
    }
    
    COVER_LETTER_TEMPLATE = """{date}

Hiring Manager
{company_name}
{company_address}

**RE: {position} Position**

Dear Hiring Manager,

I am writing to express my strong interest in the {position} position at {company_name}. With my background in {field}, I am confident that I would be a valuable addition to your team.

{experience_paragraph}

{skills_paragraph}

{why_company_paragraph}

I am excited about the opportunity to contribute to {company_name}'s success and would welcome the chance to discuss how my qualifications align with your needs.

Thank you for considering my application.

Sincerely,
{applicant_name}
{phone}
{email}"""

    REPORT_TEMPLATE = """# {title}

**Date:** {date}
**Author:** {author}
**Subject:** {subject}

## Executive Summary
{executive_summary}

## Introduction
{introduction}

## Findings / Analysis
{findings}

## Recommendations
{recommendations}

## Conclusion
{conclusion}

## Next Steps
{next_steps}

---
*Report generated by K-LYNX AI++ Professional Writer*"""

    PROPOSAL_TEMPLATE = """# PROPOSAL: {title}

**Prepared For:** {client_name}
**Prepared By:** {prepared_by}
**Date:** {date}

## 1. Executive Summary
{executive_summary}

## 2. Project Overview
{overview}

## 3. Scope of Work
{scope}

## 4. Timeline
{timeline}

## 5. Budget / Investment
{budget}

## 6. Terms & Conditions
{terms}

## 7. Next Steps
{next_steps}

---
*Proposal prepared by K-LYNX AI++ Professional Writer*"""

    @staticmethod
    def detect_writing_request(message):
        """Detect if user is asking for professional writing help"""
        msg_lower = message.lower()
        
        writing_keywords = {
            'email': ['write an email', 'draft an email', 'compose an email', 'email about', 'business email'],
            'cover_letter': ['cover letter', 'job application', 'apply for job', 'cover letter for'],
            'proposal': ['write a proposal', 'draft a proposal', 'business proposal', 'project proposal'],
            'report': ['write a report', 'draft a report', 'business report', 'project report'],
            'thank_you': ['thank you email', 'thank you note', 'appreciation email'],
            'follow_up': ['follow up email', 'follow-up email', 'follow up message'],
            'apology': ['apology email', 'sorry email', 'apologize'],
            'meeting': ['meeting request', 'schedule meeting', 'meeting invitation'],
            'introduction': ['introduction email', 'intro email', 'introduce myself'],
            'resignation': ['resignation letter', 'resignation email', 'quit job']
        }
        
        for task, keywords in writing_keywords.items():
            for keyword in keywords:
                if keyword in msg_lower:
                    return task, message
        return None, None
    
    @staticmethod
    def generate_email(email_type, context):
        """Generate a professional email"""
        template = ProfessionalWriter.EMAIL_TEMPLATES.get(email_type, ProfessionalWriter.EMAIL_TEMPLATES['business'])
        
        # Fill in defaults if not provided
        context.setdefault('recipient', '[Recipient Name]')
        context.setdefault('topic', '[Topic]')
        context.setdefault('details', '[Please provide more details about the purpose of this email]')
        context.setdefault('signature', '[Your Name]')
        context.setdefault('duration', '30-minute')
        context.setdefault('name', '[Your Name]')
        context.setdefault('executive_summary', '[Brief overview of the proposal]')
        context.setdefault('solution', '[Detailed solution description]')
        context.setdefault('timeline', '[Proposed timeline]')
        context.setdefault('investment', '[Cost/budget details]')
        
        subject = template['subject'].format(**context)
        body = template['body'].format(**context)
        
        return f"""📧 **{subject.upper()}**

{body}

---
✨ *Need adjustments? Tell me what to change!*"""
    
    @staticmethod
    def generate_cover_letter(context):
        """Generate a professional cover letter"""
        context.setdefault('date', datetime.now().strftime("%B %d, %Y"))
        context.setdefault('company_name', '[Company Name]')
        context.setdefault('company_address', '[Company Address]')
        context.setdefault('position', '[Position Title]')
        context.setdefault('field', '[Your Field/Industry]')
        context.setdefault('experience_paragraph', 'With [X] years of experience in [field], I have developed strong skills in [key skills]. My background includes [notable achievement].')
        context.setdefault('skills_paragraph', 'I bring expertise in [skill 1], [skill 2], and [skill 3]. I am proficient in [tools/technologies].')
        context.setdefault('why_company_paragraph', f"I am particularly drawn to {context.get('company_name', '[Company Name]')} because of [specific reason]. I admire your work in [area] and would love to contribute.")
        context.setdefault('applicant_name', '[Your Full Name]')
        context.setdefault('phone', '[Your Phone Number]')
        context.setdefault('email', '[Your Email Address]')
        
        cover_letter = ProfessionalWriter.COVER_LETTER_TEMPLATE.format(**context)
        
        return f"""📄 **COVER LETTER - {context.get('position', '[Position]')}**

{cover_letter}

---
✨ *Need to customize? Tell me what to add or change!*"""
    
    @staticmethod
    def generate_report(context):
        """Generate a professional report"""
        context.setdefault('title', '[Report Title]')
        context.setdefault('date', datetime.now().strftime("%B %d, %Y"))
        context.setdefault('author', '[Author Name]')
        context.setdefault('subject', '[Report Subject]')
        context.setdefault('executive_summary', '[Brief summary of key findings and recommendations]')
        context.setdefault('introduction', '[Background and purpose of the report]')
        context.setdefault('findings', '[Key findings and analysis]')
        context.setdefault('recommendations', '[Actionable recommendations]')
        context.setdefault('conclusion', '[Summary and closing thoughts]')
        context.setdefault('next_steps', '[Proposed next actions]')
        
        report = ProfessionalWriter.REPORT_TEMPLATE.format(**context)
        
        return f"""📊 **PROFESSIONAL REPORT**

{report}

---
✨ *Need changes? Let me know what to modify!*"""
    
    @staticmethod
    def generate_proposal(context):
        """Generate a business proposal"""
        context.setdefault('title', '[Proposal Title]')
        context.setdefault('client_name', '[Client Name]')
        context.setdefault('prepared_by', '[Your Name/Company]')
        context.setdefault('date', datetime.now().strftime("%B %d, %Y"))
        context.setdefault('executive_summary', '[Brief overview of the proposal]')
        context.setdefault('overview', '[Project background and objectives]')
        context.setdefault('scope', '[Detailed scope of work]')
        context.setdefault('timeline', '[Project timeline and milestones]')
        context.setdefault('budget', '[Cost breakdown and payment terms]')
        context.setdefault('terms', '[Terms and conditions]')
        context.setdefault('next_steps', '[Actions to proceed]')
        
        proposal = ProfessionalWriter.PROPOSAL_TEMPLATE.format(**context)
        
        return f"""📋 **BUSINESS PROPOSAL**

{proposal}

---
✨ *Need revisions? Tell me what to adjust!*"""
    
    @staticmethod
    def generate_resignation_letter(context):
        """Generate a professional resignation letter"""
        context.setdefault('date', datetime.now().strftime("%B %d, %Y"))
        context.setdefault('recipient', '[Manager Name]')
        context.setdefault('position', '[Your Position]')
        context.setdefault('company', '[Company Name]')
        context.setdefault('last_day', '[Last Working Day]')
        context.setdefault('reason', 'personal reasons')
        context.setdefault('appreciation', 'I am grateful for the opportunities I have had while working here.')
        
        letter = f"""📄 **RESIGNATION LETTER**

{context['date']}

Dear {context['recipient']},

Please accept this letter as formal notification of my resignation from the position of {context['position']} at {context['company']}. My last day will be {context['last_day']}.

I have decided to leave due to {context['reason']}. {context['appreciation']}

I will ensure a smooth transition of my responsibilities before my departure. I am committed to helping train any replacement or document my current projects.

Thank you for the opportunities for professional and personal development during my time here.

Sincerely,
[Your Signature]
[Your Printed Name]

---
✨ *Need to customize the reason or add anything? Let me know!*"""
        
        return letter
    
    @staticmethod
    def generate_response(task, user_message):
        """Generate a response based on detected writing task"""
        msg_lower = user_message.lower()
        
        # Extract key information from user message
        context = {}
        
        # Extract recipient name
        recipient_match = re.search(r'(?:to|for)\s+([A-Za-z\s]+?)(?:\s+about|\s+regarding|$|\.)', msg_lower)
        if recipient_match:
            context['recipient'] = recipient_match.group(1).strip().title()
        
        # Extract topic
        topic_match = re.search(r'(?:about|regarding|for)\s+(.+?)(?:\?|$| please| i need)', msg_lower)
        if topic_match:
            context['topic'] = topic_match.group(1).strip().capitalize()
        else:
            context['topic'] = "your request"
        
        # Extract position for cover letter
        position_match = re.search(r'(?:for|position of|role of)\s+([A-Za-z\s]+?)(?:\s+at|\s+in|\?|$)', msg_lower)
        if position_match:
            context['position'] = position_match.group(1).strip().title()
        
        # Extract company name
        company_match = re.search(r'(?:at|for)\s+([A-Za-z\s]+?(?:Inc|Corp|LLC|Ltd|Company|Technologies))', msg_lower, re.IGNORECASE)
        if company_match:
            context['company_name'] = company_match.group(1).strip()
        
        if task == 'email':
            if 'thank' in msg_lower:
                email_type = 'thank_you'
            elif 'follow' in msg_lower or 'update' in msg_lower:
                email_type = 'follow_up'
            elif 'sorry' in msg_lower or 'apolog' in msg_lower:
                email_type = 'apology'
            elif 'request' in msg_lower or 'ask' in msg_lower:
                email_type = 'request'
            elif 'meeting' in msg_lower or 'schedule' in msg_lower:
                email_type = 'meeting'
            elif 'intro' in msg_lower or 'introduce' in msg_lower:
                email_type = 'introduction'
            elif 'proposal' in msg_lower:
                email_type = 'proposal'
            else:
                email_type = 'business'
            
            context['details'] = f"I would like to discuss {context.get('topic', 'this matter')} with you."
            return ProfessionalWriter.generate_email(email_type, context)
        
        elif task == 'cover_letter':
            return ProfessionalWriter.generate_cover_letter(context)
        
        elif task == 'proposal':
            return ProfessionalWriter.generate_proposal(context)
        
        elif task == 'report':
            return ProfessionalWriter.generate_report(context)
        
        elif task == 'resignation':
            return ProfessionalWriter.generate_resignation_letter(context)
        
        elif task == 'thank_you':
            context['details'] = "Your support and consideration mean a great deal to me."
            return ProfessionalWriter.generate_email('thank_you', context)
        
        elif task == 'follow_up':
            context['details'] = "I wanted to check if you had a chance to review our previous conversation."
            return ProfessionalWriter.generate_email('follow_up', context)
        
        elif task == 'apology':
            context['details'] = "I take full responsibility and will ensure this doesn't happen again."
            return ProfessionalWriter.generate_email('apology', context)
        
        elif task == 'meeting':
            context['duration'] = "30-minute"
            context['details'] = "I believe a conversation would be valuable to align on next steps."
            return ProfessionalWriter.generate_email('meeting', context)
        
        elif task == 'introduction':
            context['details'] = "I believe there may be opportunities for collaboration between us."
            return ProfessionalWriter.generate_email('introduction', context)
        
        else:
            return ProfessionalWriter.get_writing_help()
    
    @staticmethod
    def get_writing_help():
        """Provide help message for writing assistance"""
        return """✍️ **Professional Writing Assistant**

I can help you write:

📧 **Emails** - Business, thank you, follow-up, apology, meeting requests
📄 **Cover Letters** - Job applications
📋 **Proposals** - Business proposals
📊 **Reports** - Professional reports
✉️ **Resignation Letters** - Professional resignation

**Try saying:**
• "Write a business email to John about our project"
• "Help me write a cover letter for a software engineer position"
• "Draft a proposal for a web development project"
• "Write a thank you email to my team"
• "Create a resignation letter"

What would you like me to write today?"""


class ProfessionalWriterHandler:
    """Handler for professional writing requests in the main chat"""
    
    @staticmethod
    def handle_writing_request(message):
        """Process writing requests from users"""
        task, user_message = ProfessionalWriter.detect_writing_request(message)
        
        if task:
            return ProfessionalWriter.generate_response(task, user_message)
        
        return None
    
    @staticmethod
    def is_writing_request(message):
        """Check if message is a writing request"""
        writing_indicators = [
            'write a', 'draft a', 'compose a', 'create a',
            'email', 'letter', 'proposal', 'report', 'cover letter',
            'resignation', 'thank you note', 'apology', 'meeting request'
        ]
        msg_lower = message.lower()
        return any(indicator in msg_lower for indicator in writing_indicators)
    
    @staticmethod
    def get_writing_help():
        """Get writing help message"""
        return ProfessionalWriter.get_writing_help()